---
- name: Docker Deployment Playbook
  hosts: private_ec2s
  become: true
  tasks:
    - name: Install dependencies for Docker
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update apt and install Docker
      ansible.builtin.package:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Ensure Docker service is started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image
      ansible.builtin.docker_image:
        name: "asmaamaged/depi-final-project:latest"
        source: pull

    - name: Stop all running containers (if any)
      ansible.builtin.shell: |
        docker ps -q | xargs -r docker stop
      ignore_errors: true

    - name: Remove all stopped containers
      ansible.builtin.shell: |
        docker ps -aq | xargs -r docker rm
      ignore_errors: true

    - name: Run Docker container
      ansible.builtin.docker_container:
        name: depi_container
        image: asmaamaged/depi-final-project:latest
        state: started
        ports:
          - "3000:3000"
        detach: true

