---
- name: Remove Apache server
  hosts: webservers
  become: yes
  tasks:
    - name: Remove Apache
      apt:
        name: apache2
        state: absent
    - name: Remove index.html
      file:
        path: /var/www/html/index.html
        state: absent

